services:
  database:
    container_name: bot_database
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER:-test}
      - POSTGRES_DB=${DB_NAME:-test}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-test}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U test" ]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - default



volumes:
  postgres_data:

networks:
  default:
    driver: bridge