"""removed_field_code

Revision ID: 005
Revises: 004
Create Date: 2025-03-30 01:32:44.632480

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "005"
down_revision: Union[str, None] = "004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("movies_code_key", "movies", type_="unique")
    op.drop_column("movies", "code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "movies", sa.Column("code", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("movies_code_key", "movies", ["code"])
    # ### end Alembic commands ###
